### PR TITLE
Add expressions, function syntax

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by olafmaas** [comment]
The grammar for the method declaration is not correct. For example the declaration 
`function(1+2){}` is accepted in this grammar. :stuck_out_tongue:    Committing the .mvn directory is not a good idea in my opinion, this will only lead to merge conflicts in the future. If you fix these things you can merge.

**Comment by ghost** [comment]
The decleration `function(1,2){}` is not accepted in this grammar. I removed the .mvn directory.

**Comment by olafmaas** [comment]
Sorry, I made a typo. `function a(1+2){
    return 0;
}` is accepted. This can easily be fixed by using a specific parameter type instead of the Expression type.

**Comment by ghost** [comment]
You are right. We never have a function definition in the way we use it. But you need it. I hope this is the way you want it. It is now an `<ID>`

**Comment by olafmaas** [comment]
Perfect! :+1:  :shipit:

**Pull request merged**
